DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS receptions CASCADE;
DROP TABLE IF EXISTS pvz CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP INDEX IF EXISTS unique_active_reception;
DROP EXTENSION IF EXISTS "uuid-ossp";