// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/mi4r/avito-pvz/internal/storage"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PVZRepository is an autogenerated mock type for the PVZRepository type
type PVZRepository struct {
	mock.Mock
}

// CreatePVZ provides a mock function with given fields: ctx, city
func (_m *PVZRepository) CreatePVZ(ctx context.Context, city string) (storage.PVZ, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 storage.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (storage.PVZ, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) storage.PVZ); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Get(0).(storage.PVZ)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPVZsWithReceptions provides a mock function with given fields: ctx, startDate, endDate, page, limit
func (_m *PVZRepository) GetPVZsWithReceptions(ctx context.Context, startDate time.Time, endDate time.Time, page int, limit int) ([]storage.PVZWithReceptions, error) {
	ret := _m.Called(ctx, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZsWithReceptions")
	}

	var r0 []storage.PVZWithReceptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]storage.PVZWithReceptions, error)); ok {
		return rf(ctx, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []storage.PVZWithReceptions); ok {
		r0 = rf(ctx, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.PVZWithReceptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, startDate, endDate, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPVZRepository creates a new instance of PVZRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPVZRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PVZRepository {
	mock := &PVZRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
