// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/mi4r/avito-pvz/internal/storage"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, receptionID, productType
func (_m *Storage) AddProduct(ctx context.Context, receptionID uuid.UUID, productType string) (storage.Product, error) {
	ret := _m.Called(ctx, receptionID, productType)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 storage.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (storage.Product, error)); ok {
		return rf(ctx, receptionID, productType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) storage.Product); ok {
		r0 = rf(ctx, receptionID, productType)
	} else {
		r0 = ret.Get(0).(storage.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, receptionID, productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CloseReception provides a mock function with given fields: ctx, receptionID
func (_m *Storage) CloseReception(ctx context.Context, receptionID uuid.UUID) error {
	ret := _m.Called(ctx, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for CloseReception")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, receptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePVZ provides a mock function with given fields: ctx, city
func (_m *Storage) CreatePVZ(ctx context.Context, city string) (storage.PVZ, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 storage.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (storage.PVZ, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) storage.PVZ); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Get(0).(storage.PVZ)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateReception provides a mock function with given fields: ctx, pvzID
func (_m *Storage) CreateReception(ctx context.Context, pvzID uuid.UUID) (storage.Reception, error) {
	ret := _m.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for CreateReception")
	}

	var r0 storage.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (storage.Reception, error)); ok {
		return rf(ctx, pvzID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) storage.Reception); ok {
		r0 = rf(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(storage.Reception)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, email, passwordHash, role
func (_m *Storage) CreateUser(ctx context.Context, email string, passwordHash string, role string) (storage.User, error) {
	ret := _m.Called(ctx, email, passwordHash, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (storage.User, error)); ok {
		return rf(ctx, email, passwordHash, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) storage.User); ok {
		r0 = rf(ctx, email, passwordHash, role)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, productID
func (_m *Storage) DeleteProduct(ctx context.Context, productID uuid.UUID) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastProduct provides a mock function with given fields: ctx, receptionID
func (_m *Storage) GetLastProduct(ctx context.Context, receptionID uuid.UUID) (storage.Product, error) {
	ret := _m.Called(ctx, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastProduct")
	}

	var r0 storage.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (storage.Product, error)); ok {
		return rf(ctx, receptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) storage.Product); ok {
		r0 = rf(ctx, receptionID)
	} else {
		r0 = ret.Get(0).(storage.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, receptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpenReception provides a mock function with given fields: ctx, pvzID
func (_m *Storage) GetOpenReception(ctx context.Context, pvzID uuid.UUID) (storage.Reception, error) {
	ret := _m.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenReception")
	}

	var r0 storage.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (storage.Reception, error)); ok {
		return rf(ctx, pvzID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) storage.Reception); ok {
		r0 = rf(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(storage.Reception)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPVZsWithReceptions provides a mock function with given fields: ctx, startDate, endDate, page, limit
func (_m *Storage) GetPVZsWithReceptions(ctx context.Context, startDate time.Time, endDate time.Time, page int, limit int) ([]storage.PVZWithReceptions, error) {
	ret := _m.Called(ctx, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZsWithReceptions")
	}

	var r0 []storage.PVZWithReceptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]storage.PVZWithReceptions, error)); ok {
		return rf(ctx, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []storage.PVZWithReceptions); ok {
		r0 = rf(ctx, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.PVZWithReceptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, startDate, endDate, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Storage) GetUserByEmail(ctx context.Context, email string) (storage.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (storage.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) storage.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
